import { AptitudeQuestion } from '../types';

export const APTITUDE_QUESTIONS_BANK: AptitudeQuestion[] = [
  // ==================== QUANTITATIVE ABILITY ====================
  {
    id: 'apt_q_1',
    skillId: 'aptitude_general',
    topic: 'Percentages & Growth Metrics',
    difficulty: 'easy',
    aptitudeCategory: 'QUANTITATIVE',
    questionText: 'A SaaS platform increased its monthly recurring revenue (MRR) from $50,000 to $65,000 in Q2. What was the percentage growth rate of MRR in Q2?',
    options: ['20%', '25%', '30%', '35%'],
    correctIndex: 2,
    explanation: 'Percentage Growth = ((New Value - Old Value) / Old Value) * 100. Growth = ($65,000 - $50,000) / $50,000 = $15,000 / $50,000 = 0.30 = 30%.',
    tags: ['Percentages', 'Finance', 'SaaS Metrics']
  },
  {
    id: 'apt_q_2',
    skillId: 'aptitude_general',
    topic: 'Ratios & Work Rate',
    difficulty: 'medium',
    aptitudeCategory: 'QUANTITATIVE',
    questionText: 'Developer A can build an API module in 6 hours alone, and Developer B can build the same API module in 12 hours alone. Working together synchronously, how many hours will they take to complete the API module?',
    options: ['3 hours', '4 hours', '4.5 hours', '5 hours'],
    correctIndex: 1,
    explanation: 'Rate of Dev A = 1/6 job per hour. Rate of Dev B = 1/12 job per hour. Combined rate = 1/6 + 1/12 = 2/12 + 1/12 = 3/12 = 1/4 job per hour. Total time = 1 / (1/4) = 4 hours.',
    tags: ['Work & Time', 'Ratios', 'Engineering Efficiency']
  },
  {
    id: 'apt_q_3',
    skillId: 'aptitude_general',
    topic: 'Probability & System Reliability',
    difficulty: 'hard',
    aptitudeCategory: 'QUANTITATIVE',
    questionText: 'A high-availability cloud architecture routes traffic through two redundant server nodes operating independently. Node A has an operational availability probability of 0.95, and Node B has an operational availability probability of 0.90. What is the probability that AT LEAST ONE node is operational to handle incoming requests?',
    options: ['0.855', '0.985', '0.995', '0.925'],
    correctIndex: 2,
    explanation: 'P(At least one operational) = 1 - P(Both fail). Failure of Node A = 1 - 0.95 = 0.05. Failure of Node B = 1 - 0.90 = 0.10. P(Both fail) = 0.05 * 0.10 = 0.005. Therefore, P(At least one operational) = 1 - 0.005 = 0.995 (99.5%).',
    tags: ['Probability', 'Cloud Availability', 'Redundancy']
  },

  // ==================== LOGICAL REASONING ====================
  {
    id: 'apt_l_1',
    skillId: 'aptitude_general',
    topic: 'Series & Pattern Deduction',
    difficulty: 'easy',
    aptitudeCategory: 'LOGICAL',
    questionText: 'Identify the next term in the logical sequence: 3, 7, 15, 31, 63, ?',
    options: ['95', '125', '127', '129'],
    correctIndex: 2,
    explanation: 'Each term is generated by (Previous Term * 2) + 1. (3*2+1=7), (7*2+1=15), (15*2+1=31), (31*2+1=63). Therefore, Next Term = (63*2)+1 = 126 + 1 = 127.',
    tags: ['Series', 'Pattern Detection']
  },
  {
    id: 'apt_l_2',
    skillId: 'aptitude_general',
    topic: 'Syllogism & Deductive Logic',
    difficulty: 'medium',
    aptitudeCategory: 'LOGICAL',
    questionText: 'Premise 1: All relational databases use ACID transactions.\nPremise 2: PostgreSQL is a relational database.\nPremise 3: No MongoDB collection uses relational joins.\nWhich of the following MUST be logically true?',
    options: [
      'PostgreSQL uses ACID transactions.',
      'MongoDB uses ACID transactions.',
      'All databases with ACID transactions are PostgreSQL.',
      'Relational databases cannot process document JSONs.'
    ],
    correctIndex: 0,
    explanation: 'By categorical syllogism: Premise 1 states All Relational Databases -> ACID. Premise 2 states PostgreSQL -> Relational Database. Therefore, PostgreSQL -> ACID transactions must be true.',
    tags: ['Syllogism', 'Deductive Logic']
  },
  {
    id: 'apt_l_3',
    skillId: 'aptitude_general',
    topic: 'Conditional Logic & Troubleshooting',
    difficulty: 'hard',
    aptitudeCategory: 'LOGICAL',
    questionText: 'An incident report states:\n1. If the database connection pool is exhausted, the server returns a 504 Gateway Timeout or 500 Internal Server Error.\n2. If the memory usage exceeds 90%, the server crashes.\n3. The server did NOT crash, and returned a 504 Gateway Timeout.\nWhich conclusion is logically sound?',
    options: [
      'Memory usage exceeded 90%.',
      'The database connection pool MAY be exhausted.',
      'The database connection pool is definitely NOT exhausted.',
      'The server was shut down manually.'
    ],
    correctIndex: 1,
    explanation: 'Rule 1: Connection Pool Exhausted -> 504 OR 500. Experiencing 504 means connection pool exhaustion is a valid possible cause. Rule 2: Memory > 90% -> Crash. Since it did NOT crash, memory was <= 90%.',
    tags: ['Conditionals', 'Incident Analysis']
  },

  // ==================== VERBAL COMPREHENSION ====================
  {
    id: 'apt_v_1',
    skillId: 'aptitude_general',
    topic: 'Technical Reading Comprehension',
    difficulty: 'easy',
    aptitudeCategory: 'VERBAL',
    dataSnippet: {
      type: 'passage',
      title: 'Microservices Architecture Excerpt',
      content: 'Monolithic applications consolidate business logic into a single deployment binary. While easy to build initially, scaling individual components requires scaling the entire stack. Conversely, microservices decouple domain services into independently deployable units communicating over HTTP/gRPC. This isolation minimizes blast radiuses during deployment failures but introduces distributed state complexity.'
    },
    questionText: 'Based on the passage above, what is identified as a primary trade-off when adopting microservices?',
    options: [
      'Microservices make initial application builds faster.',
      'Microservices introduce distributed state complexity in exchange for isolated deployments.',
      'Microservices force all communication to occur over monolithic binaries.',
      'Microservices increase the blast radius of deployment failures.'
    ],
    correctIndex: 1,
    explanation: 'The passage explicitly states: "This isolation minimizes blast radiuses... but introduces distributed state complexity."',
    tags: ['Comprehension', 'Architecture']
  },
  {
    id: 'apt_v_2',
    skillId: 'aptitude_general',
    topic: 'Logical Fallacy & Critical Reasoning',
    difficulty: 'medium',
    aptitudeCategory: 'VERBAL',
    questionText: 'A team lead claims: "We switched our frontend framework to React, and our user engagement grew by 40% in Q3. Therefore, React directly caused our user growth." What logical fallacy is committed in this argument?',
    options: [
      'Ad Hominem (Attacking the person)',
      'Post Hoc Ergo Propter Hoc (False Cause / Confounding correlation with causation)',
      'Straw Man (Misrepresenting the opposing view)',
      'Circular Reasoning (Begging the question)'
    ],
    correctIndex: 1,
    explanation: 'Post hoc ergo propter hoc assumes that because B occurred after A, A caused B. It ignores other Q3 growth factors like marketing, seasonal trends, or feature launches.',
    tags: ['Critical Thinking', 'Logical Fallacies']
  },

  // ==================== DATA INTERPRETATION ====================
  {
    id: 'apt_d_1',
    skillId: 'aptitude_general',
    topic: 'Tabular Data Analysis',
    difficulty: 'easy',
    aptitudeCategory: 'DATA_INTERPRETATION',
    dataSnippet: {
      type: 'table',
      title: 'Q1 Regional Cloud Expenses ($ in Thousands)',
      content: JSON.stringify([
        { Region: 'US-East', Compute: 40, Storage: 20, Bandwidth: 10 },
        { Region: 'EU-West', Compute: 30, Storage: 15, Bandwidth: 15 },
        { Region: 'AP-South', Compute: 50, Storage: 25, Bandwidth: 25 }
      ])
    },
    questionText: 'According to the table above, what percentage of AP-South total expense is attributed to Compute costs?',
    options: ['40%', '50%', '60%', '25%'],
    correctIndex: 1,
    explanation: 'Total AP-South expense = 50 (Compute) + 25 (Storage) + 25 (Bandwidth) = 100 ($k). Compute ratio = 50 / 100 = 50%.',
    tags: ['Data Interpretation', 'Tabular Analytics']
  },
  {
    id: 'apt_d_2',
    skillId: 'aptitude_general',
    topic: 'Metric Conversion & Trend Analysis',
    difficulty: 'medium',
    aptitudeCategory: 'DATA_INTERPRETATION',
    dataSnippet: {
      type: 'table',
      title: 'Customer Conversion Funnel Metrics',
      content: JSON.stringify([
        { Stage: '1. Website Visitors', Count: 100000 },
        { Stage: '2. Sign-ups', Count: 10000 },
        { Stage: '3. Active Trial Users', Count: 4000 },
        { Stage: '4. Paid Subscriptions', Count: 1000 }
      ])
    },
    questionText: 'What is the overall conversion rate from Website Visitors directly to Paid Subscriptions, AND what is the conversion rate from Active Trial Users to Paid Subscriptions?',
    options: [
      '1.0% overall, and 25.0% trial-to-paid',
      '10.0% overall, and 10.0% trial-to-paid',
      '0.1% overall, and 40.0% trial-to-paid',
      '2.5% overall, and 15.0% trial-to-paid'
    ],
    correctIndex: 0,
    explanation: 'Overall conversion = 1,000 / 100,000 = 0.01 = 1.0%. Trial-to-paid conversion = 1,000 / 4,000 = 0.25 = 25.0%.',
    tags: ['Funnel Analysis', 'Conversion Rates']
  },

  // ==================== SYSTEM & ABSTRACT REASONING ====================
  {
    id: 'apt_s_1',
    skillId: 'aptitude_general',
    topic: 'Pseudocode Tracing & Algorithmic State',
    difficulty: 'easy',
    aptitudeCategory: 'SYSTEM_ABSTRACT',
    dataSnippet: {
      type: 'pseudocode',
      title: 'Algorithm Trace',
      content: `x = 1
y = 10
while x < y:
    x = x * 2
    y = y - 1
print(x, y)`
    },
    questionText: 'What values of x and y will be printed when the pseudocode loop finishes execution?',
    options: ['x = 8, y = 7', 'x = 4, y = 8', 'x = 16, y = 6', 'x = 8, y = 6'],
    correctIndex: 0,
    explanation: 'Iteration 1: x=1, y=10 -> x=2, y=9. (2 < 9, continue).\nIteration 2: x=2, y=9 -> x=4, y=8. (4 < 8, continue).\nIteration 3: x=4, y=8 -> x=8, y=7. (8 < 7 is FALSE, loop terminates).\nFinal values: x = 8, y = 7.',
    tags: ['Pseudocode', 'Loop Tracing']
  },
  {
    id: 'apt_s_2',
    skillId: 'aptitude_general',
    topic: 'Flowchart Logic & State Transitions',
    difficulty: 'medium',
    aptitudeCategory: 'SYSTEM_ABSTRACT',
    dataSnippet: {
      type: 'pseudocode',
      title: 'State Machine Retry Algorithm',
      content: `status = "PENDING"
retries = 0
max_retries = 3

def process_request():
  global status, retries
  while retries < max_retries:
    success = attempt_connection()
    if success:
      status = "COMPLETED"
      return
    else:
      retries += 1
  status = "FAILED"`
    },
    questionText: 'If attempt_connection() returns False on the 1st attempt, False on the 2nd attempt, and True on the 3rd attempt, what will be the final value of "status" and "retries"?',
    options: [
      'status = "COMPLETED", retries = 2',
      'status = "FAILED", retries = 3',
      'status = "COMPLETED", retries = 3',
      'status = "PENDING", retries = 2'
    ],
    correctIndex: 0,
    explanation: 'Attempt 1: success=False -> retries becomes 1.\nAttempt 2: success=False -> retries becomes 2.\nAttempt 3: success=True -> status becomes "COMPLETED", return triggers immediately.\nFinal state: status = "COMPLETED", retries = 2.',
    tags: ['State Machine', 'Retry Logic']
  }
];
